[tool.black]
line_length = 120

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 2
include_trailing_comma = true
force_single_line = false
#known_first_party = ["myproject"]
#skip = ["migrations"]
